# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 11:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form_example', '0002_collage_city'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='collage',
            table='college',
        ),
    ]
