# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-17 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_example', '0003_auto_20181117_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fathername', models.CharField(max_length=20)),
                ('phonenumber', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=500)),
            ],
        ),
    ]
